### ISSUE TITLE
Where the hell is sample configs?

### ISSUE THREAD

**Issue by futilityteam** [Emzi0767/Discord-ASM-Bot#1]
WTF?

**Comment by Emzi0767** [comment]
Not in the repo I guess. I don't really support self-hosting on this, you can prolly reverse engineer the config format from the launcher code.

**Comment by futilityteam** [comment]
Self-hosting? Do you have other ways of hosting? Will you send your config with the important things removed?

**Comment by Emzi0767** [comment]
My config is a docker secret, which is not a plain file. You can use the public instance of the bot, by inviting it via this link: https://emzi0767.com/Discord/Asm/invite

**Comment by Emzi0767** [comment]
Closed for inactivity.

**Comment by ghost** [comment]
> My config is a docker secret, which is not a plain file. You can use the public instance of the bot, by inviting it via this link: https://emzi0767.com/Discord/Asm/invite

[link moved?](https://emzi0767.com/#!/discord/asm)
And if possible, can you add my server?
> This integration is private. Only the application owner can add it.
